services:
  - type: web
    plan: free
    name: Simple-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/TN69Links-Saravana/Simple-Rename-Bot.git      
    branch: main
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: ADMINS
        sync: false
      - key: CAPTION
        sync: false
    autoDeploy: false
