services:
  - type: web
    plan: free
    name: Simple-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/TN69Links-Saravana/Simple-Rename-Bot
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: 6433110243:AAEHTsio1VnTpliE78Z02AzImHJFrIM6VYQ
      - key: API_ID
        sync: 24482734
      - key: API_HASH
        sync: 5ccf6a58166cc047a7eba01c5dbc930c
      - key: CAPTION
        sync: <b>{file_name}</b>
      - key: ADMIN
        sync: 1790775725

        
